application: budget-master-reston
version: 1
runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /.*
  script: routes.router
  

env_variables:
    CLOUDSQL_CONNECTION_NAME: budget-master-reston:us-east1:budgetize
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: MartaLiesseChiara

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"
  